version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  cord:
    image: dhiway/cord:7daf20a59131bf672c205033b953c218bcea26d9
    ports:
      - 9944:9944
      - 9933:9933
    volumes:
      - .data/cord:/cord/.local/share
    command:
      - --dev
      - --unsafe-ws-external
      - --unsafe-rpc-external

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3001:3000
    depends_on:
      - "postgres"
      - "cord"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=cord
      - --playground

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
      - "cord"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --subquery-name=cord
      - --migrate
